import "./globals.css";
import AuthProvider from "./{components}/AuthProvider";
import Nav from "./{components}/Nav";
import { PantryProvider } from "./{components}/PantryProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <PantryProvider>
            <Nav />
            <div>{children}</div>
          </PantryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
