import AuthProvider from "../(dashboard)/{components}/AuthProvider";
import { Analytics } from "@vercel/analytics/react"
import "../globals.css"
import Nav from "./{components}/Nav";

export const metadata = {
  title: "Pantry AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <AuthProvider>
        <div>
          <Nav />
          {children}
        </div>
      </AuthProvider>
      <Analytics />
      </body>
    </html>
  );
}
