import "../globals.css";
import AuthProvider from "./{components}/AuthProvider";
import { PantryProvider } from "./{components}/PantryProvider";
import { SidebarDemo } from "./{components}/Sidebar";
import { cn } from "@/lib/utils";

export const metadata = {
  title: "Pantry AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <PantryProvider>
            <div className={cn(
              "flex md:flex-row flex-col w-full h-[100vh]",
            )}>
              <SidebarDemo className="w-1/4 md:w-1/5" />
              <div className="flex-1 overflow-auto">
                {children}
              </div>
            </div>
          </PantryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
